added carousel to home page
CodeTheDream/not-alone pull request #16
Opened 2021-01-04 00:55 UTC by OksanaWeigandSuminski

Hey @jrmcgarvey! Here is a carousel of images on the home page. Let me know if it's ok.

2021-01-04 02:24 UTC, jrmcgarvey requested changes
Oksana, I would like to see a couple of changes.

See the inline comment about use of the alt tags -- we need phrases that describe the image.  Also, we have to avoid including .DS_Store files, perhaps by something in .gitignore.  Those files don't really belong in the git repository, although I think we have some of them already.

2021-01-04 02:24 UTC, jrmcgarvey commented on app/views/home/index.html.erb
> +      <img class="d-block w-100" src="/assets/1.jpg" alt="First slide" style="align-content: center;">
We need to put something descriptive for the alt values.  It should be a few words that says what the slide shows.  The purpose of the alt is to convey meaning to those who can't see the image.  "first slide" doesn't convey any meaning.

2021-01-07 21:45 UTC, OksanaWeigandSuminski commented
I made changes. Please take a look @jrmcgarvey.

2021-01-07 21:48 UTC, jrmcgarvey approved these changes
Looks ok now

2021-01-07 21:48 UTC, merged