questionnaire is added
CodeTheDream/not-alone pull request #33
Opened 2021-01-19 01:10 UTC by NataMarkova

@jrmcgarvey, please check it out. This PR consists of adding a questionnaire (Healthy Relationship table) first page without a scoring page

2021-01-20 00:55 UTC, jrmcgarvey requested changes
Hi Natalia.  Quite a few changes are needed.  Let me know if you have questions.

2021-01-20 00:55 UTC, jrmcgarvey commented on app/views/home/health.html.erb
> +<!DOCTYPE html>
These initial lines should not be present.  Everything down to the body tag comes from the app/views/layout/application.html.erb.  You should remove everything down to and including the body tag, and do the same at the end of the file -- remove everything starting with the /body tag

2021-01-20 00:55 UTC, jrmcgarvey commented on app/views/home/health.html.erb
> +      <p>EVERYONE DESERVES TO BE IN A SAFE AND HEALTHY RELATIONSHIP. DO YOU KNOW IF YOUR RELATIONSHIP
I dislike the use of caps here -- it would be better if you styled this paragraph with a slightly larger font or something like that.

2021-01-20 00:55 UTC, jrmcgarvey commented on app/views/home/health.html.erb
> +            <td><input type="radio" name = "ans" value="yes"></input></td>
You have named all the inputs as "ans".  The problem with this is that when the controller receives the submit button, it will only get one value, from the last "ans" field.  You have to name each field with a different name, e.g. ans1, ans2, etc.

2021-01-20 00:55 UTC, jrmcgarvey commented on app/views/home/health.html.erb
> +        </form>
You can only have one form on a page.  The whole list of questions has to be in one form, or the submit button won't submit all of them. The form should start before the top of the table and end after the submit button.

2021-01-20 00:55 UTC, jrmcgarvey commented on app/views/home/health.html.erb
> +            <td><input type="submit" value="Submit"></td>
The submit button should not be part of the table.

2021-01-21 23:19 UTC, NataMarkova commented on app/views/home/health.html.erb
> +<!DOCTYPE html>
Fixed

2021-01-21 23:19 UTC, NataMarkova commented on app/views/home/health.html.erb
> +      <p>EVERYONE DESERVES TO BE IN A SAFE AND HEALTHY RELATIONSHIP. DO YOU KNOW IF YOUR RELATIONSHIP
Fixed

2021-01-21 23:19 UTC, NataMarkova commented on app/views/home/health.html.erb
> +            <td><input type="radio" name = "ans" value="yes"></input></td>
Fixed

2021-01-21 23:19 UTC, NataMarkova commented on app/views/home/health.html.erb
> +        </form>
Fixed

2021-01-21 23:19 UTC, NataMarkova commented on app/views/home/health.html.erb
> +            <td><input type="submit" value="Submit"></td>
Fixed

2021-01-21 23:20 UTC, NataMarkova commented
@jrmcgarvey, please check the changes out

2021-01-22 18:06 UTC, jrmcgarvey approved these changes
Looks ok now.  I will merge.

2021-01-22 18:06 UTC, merged