Created rspec for videos, sessions, services, orders, customers, assignments. Made changes in corresponding files. Changed NavBar. Rspec for assignments with errors
CodeTheDream/not-alone pull request #37
Opened 2021-01-25 01:39 UTC by lena-aiu

Hi John, please review the rspec. In assignments_request_spec.rb I have errors, need help to resolve them. Thank you @jrmcgarvey

2021-01-25 16:50 UTC, jrmcgarvey requested changes
Hi Elena.  You have merge conflicts that must be resolved.  In addition, you will need a spec/factories/assignments.rb with a Factory :assignment.  Finally, there are many changes needed in the spec/requests/assignments_request_spec.rb.  I have put in comments for that file which show some but not all of the changes that are needed.

It would be good if you would add tests to login as a user who does not have an administrator or intern role, to make sure that such a user can't create assignments or videos.

2021-01-25 16:50 UTC, jrmcgarvey commented on spec/requests/assignments_request_spec.rb
> +      get assignments_index_path
This won't work.  The assignments path is nested inside the customer path in config/routes.rb.  You can check what paths you have for assignments by doing bin/rails routes.  You will have a customer_assignments path, for which you must specify a customer_id.

2021-01-25 16:50 UTC, jrmcgarvey commented on spec/requests/assignments_request_spec.rb
> +      customer = FactoryBot.create_list(:customer, 10)
You don't need this line

2021-01-25 16:50 UTC, jrmcgarvey commented on spec/requests/assignments_request_spec.rb
> +      user = FactoryBot.create_list(:user, 10)
You don't need this line.

2021-01-25 16:50 UTC, jrmcgarvey commented on spec/requests/assignments_request_spec.rb
> +      assignment = FactoryBot.create_list(:status, 10)
You want: assignments = FactoryBot.create_list(:assignment, 10)

2021-01-25 16:50 UTC, jrmcgarvey commented on spec/requests/assignments_request_spec.rb
> +      #sign_in user
You should sign in the user here.

2021-01-25 16:50 UTC, jrmcgarvey commented on spec/requests/assignments_request_spec.rb
> +      expect(response).to be_redirect
You should check that it redirects to the right page.  Check the controller to see what page is used in the redirect.

2021-01-25 16:50 UTC, jrmcgarvey commented on spec/requests/assignments_request_spec.rb
> +    it "redirects to the index path if the assignment id is invalid" do
This test is a duplicate of a previous one

2021-01-25 16:50 UTC, jrmcgarvey commented on spec/requests/assignments_request_spec.rb
> +      expect { post assignments_path, params: {assignment: {customer_id: customer.id, user_id: user.id, status: "new"}}
This won't work, because there is no assignments path.  There is a customer_assignments_path.  The customer_assignments path takes a customer_id.  You would not have the customer_id in the params, because it is in the path.

2021-01-25 16:50 UTC, jrmcgarvey commented on spec/requests/assignments_request_spec.rb
> +      expect { post assignments_path, params: {assignment: {customer_id: customer.id, user_id: user.id, status: "new"}}
This won't work because there is no assignments_path.  You must use customer_assignments_path.

2021-01-25 16:50 UTC, jrmcgarvey commented on spec/requests/assignments_request_spec.rb
> +      assignment = FactoryBot.create(:status)
This should be FactoryBot.create(:assignment)

2021-01-25 16:50 UTC, jrmcgarvey commented on spec/requests/assignments_request_spec.rb
> +      assignment = FactoryBot.create(:status)
This should be FactoryBot.create(:assignment)

2021-01-25 16:50 UTC, jrmcgarvey commented on spec/factories/customers.rb
> +require 'faker'
You will need a spec/factories/assigments.rb with a factory :assignment.  (I thought we created that?)

2021-01-25 16:50 UTC, jrmcgarvey commented on spec/requests/assignments_request_spec.rb
> +      #sign_in user
You should sign in the user here

2021-02-01 08:24 UTC, lena-aiu commented on spec/requests/assignments_request_spec.rb
> +      #sign_in user
Got it!

2021-02-01 08:25 UTC, lena-aiu commented on spec/requests/assignments_request_spec.rb
> +      #sign_in user
Got it!

2021-02-01 08:26 UTC, lena-aiu commented on spec/requests/assignments_request_spec.rb
> +      customer = FactoryBot.create_list(:customer, 10)
Got it!

2021-02-01 08:26 UTC, lena-aiu commented on spec/requests/assignments_request_spec.rb
> +      user = FactoryBot.create_list(:user, 10)
Got it!

2021-02-01 08:27 UTC, lena-aiu commented on spec/requests/assignments_request_spec.rb
> +      assignment = FactoryBot.create_list(:status, 10)
Got it!

2021-02-01 08:28 UTC, lena-aiu commented on spec/requests/assignments_request_spec.rb
> +      assignment = FactoryBot.create(:status)
Got it!

2021-02-01 08:28 UTC, lena-aiu commented on spec/requests/assignments_request_spec.rb
> +      assignment = FactoryBot.create(:status)
Got it!

2021-02-01 08:30 UTC, lena-aiu commented on spec/factories/customers.rb
> +require 'faker'
Yes, we have it. Here spec/factories/assigments.rb
FactoryBot.define do
  factory :assignment do
    user { nil }
    customer { nil }
    status { "MyString" }
  end
end

2021-02-01 08:52 UTC, lena-aiu commented on spec/requests/assignments_request_spec.rb
> +      expect { post assignments_path, params: {assignment: {customer_id: customer.id, user_id: user.id, status: "new"}}
Got it!

2021-02-01 08:52 UTC, lena-aiu commented on spec/requests/assignments_request_spec.rb
> +      expect { post assignments_path, params: {assignment: {customer_id: customer.id, user_id: user.id, status: "new"}}
Got it!

2021-02-01 19:10 UTC, jrmcgarvey requested changes
Various changes needed.  Please test after you have made the required changes.  One change, for example, is for <<<<< >>>> conflict resolution flags in the navbar.

2021-02-01 19:10 UTC, jrmcgarvey commented on spec/requests/customers_spec.rb
> +RSpec.configure do |config|
You do not need lines 3/4/5 as the DeviseRequestSpecHelpers are already included in rails_helper.rb

2021-02-01 19:10 UTC, jrmcgarvey commented on spec/requests/videos_spec.rb
> +      expect { delete videos_path(id: video.id).to eq("new")}
Again, you want to do an expect response to redirect to a particular path here.  The expect delete videos path does not make sense.

2021-02-01 19:10 UTC, jrmcgarvey commented on spec/requests/services_spec.rb
>        expect { delete services_path(id: service.id).to eq("new")}
Again, the expect delete services path is not what we want.  You should expect the response to redirect to the index path

2021-02-01 19:10 UTC, jrmcgarvey commented on spec/requests/orders_spec.rb
> +RSpec.configure do |config|
You do not need these 3 lines as the required include is already present in rails_helper.rb

2021-02-01 19:10 UTC, jrmcgarvey commented on spec/requests/assignments_request_spec.rb
> +RSpec.configure do |config|
You do not need these lines here, as the required include is already in rails_helper.rb

2021-02-02 00:51 UTC, jrmcgarvey approved these changes
Ok, seems to be correct.  We should probably go over this code another time.

2021-02-02 00:51 UTC, merged