fixed new videos path and new services path
CodeTheDream/not-alone pull request #48
Opened 2021-02-06 20:34 UTC by NataMarkova

@jrmcgarvey, please check it out. The PR consists of fixing an issue with http://localhost:3000/en/videos/new and  http://localhost:3000/en/services/new for unauthorized users, translating a sentence en->es

2021-02-06 21:37 UTC, jrmcgarvey requested changes
Natalia, some changes are needed.  Please look at the comments.

2021-02-06 21:37 UTC, jrmcgarvey commented on app/controllers/application_controller.rb
>    def require_current_user
This routine is commented out and should be removed.

2021-02-06 21:37 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
>    before_action :require_current_user, except: [:show, :index]
This line should be removed -- it does nothing

2021-02-06 21:37 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +  before_action :admin?, except: [:show, :index]
This line does nothing useful and should be removed

2021-02-06 21:37 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +  before_action :intern?, except: [:show, :index]
This line does nothing useful and should be removed

2021-02-06 21:37 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
>    before_action :set_service, only: [:show, :edit, :update, :destroy]
This line should be moved to happen after is_user_authorized?  If the user is not authorized, we don't want to make database calls on behalf of the user.

2021-02-06 21:37 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +    def is_user_authorized?
This section is basically duplicated in services_controller.rb and videos_controller.rb.  We want to follow DRY principles: don't repeat yourself.  It should be in app/helplers/application_helper.rb, just once.

2021-02-06 21:37 UTC, jrmcgarvey commented on app/controllers/videos_controller.rb
>    before_action :set_video, only: [:show, :edit, :update, :destroy]
This line should be moved to after is_user_authorized?

2021-02-06 21:37 UTC, jrmcgarvey commented on app/controllers/videos_controller.rb
> +  before_action :admin?, except: [:show, :index]
This line should be removed.

2021-02-06 21:37 UTC, jrmcgarvey commented on app/controllers/videos_controller.rb
> +  before_action :intern?, except: [:show, :index]
This line should be removed, as it does nothing useful.

2021-02-06 21:37 UTC, jrmcgarvey commented on app/controllers/videos_controller.rb
> +
This section is basically a repeat and should be moved to app/helpers/applcation_helper.rb.

2021-02-06 21:37 UTC, jrmcgarvey commented on spec/requests/services_spec.rb
> +  describe "get new_service_path" do
These changes should not occur as part of this PR, because you will get merge conflicts with work that Elena is doing.  This file should be unchanged by this PR>

2021-02-06 22:23 UTC, NataMarkova commented on app/controllers/application_controller.rb
>    def require_current_user
Should I remove the whole method or just the stuff that are inside of the method?

2021-02-06 22:28 UTC, jrmcgarvey commented on app/controllers/application_controller.rb
>    def require_current_user
The whole method should be removed.

2021-02-06 22:28 UTC, NataMarkova commented on app/controllers/services_controller.rb
>    before_action :require_current_user, except: [:show, :index]
I'm not sure which line should be removed out of these three

2021-02-06 22:38 UTC, NataMarkova commented on app/controllers/services_controller.rb
>    before_action :require_current_user, except: [:show, :index]
After your answer on the previous comment I know which line should be removed

2021-02-07 01:35 UTC, jrmcgarvey approved these changes
Looks OK now.

2021-02-07 01:35 UTC, merged