Customer access
CodeTheDream/not-alone pull request #50
Opened 2021-02-14 19:58 UTC by NataMarkova

@jrmcgarvey, please check it out. The PR consists of feature of access control for the customer (client) views and controller. The code that I worked on doesn't handle a case when a user has restriction to the CRUD operations in assignments based on his role.

2021-02-14 21:28 UTC, jrmcgarvey requested changes
Some changes needed -- let me know if you have questions.

2021-02-14 21:28 UTC, jrmcgarvey commented on app/controllers/customers_controller.rb
> +      elsif current_user.role.include?("volunteer")
This logic is not quite right.  It is possible for someone to be a volunteer and an administrator, in which case they should see the whole list.  It is also possible that the user has a role, but that role does not include volunteer or intern or administrator, in which case they are not authorized.

Something like:

if current_user.role.nil?
  not authorized
elsif current_user.role.include?('administrator') || current_user.role.include?('intern')
 show the full list
elsif current_user.role.include?('volunteer')
 show the current user's assigned list
else
 you are not authorized
end

2021-02-14 21:28 UTC, jrmcgarvey commented on app/controllers/customers_controller.rb
> +        @customers = current_user.customers
There should be access control added for each of the other operations, not just index.  Only administrators or interns could do new, edit, create, update, or delete.  Volunteers could do show, but only for customers to which they are assigned.  Users that don't have any of these roles can't do any of the operations.

2021-02-17 01:52 UTC, NataMarkova commented on app/controllers/customers_controller.rb
> +      elsif current_user.role.include?("volunteer")
Fixed

2021-02-17 01:53 UTC, NataMarkova commented on app/controllers/customers_controller.rb
> +        @customers = current_user.customers
The logic was implemented.

2021-02-17 01:53 UTC, NataMarkova commented
@jrmcgarvey , please check it out one more time

2021-02-17 03:39 UTC, jrmcgarvey approved these changes
OK, looks correct now!  I will merge.

2021-02-17 03:39 UTC, merged