Rspec v2
CodeTheDream/not-alone pull request #77
Opened 2021-03-14 07:48 UTC by NataMarkova

Hi @jrmcgarvey! This PR consists of non-completed rspec for orders and assignments. I've got an error for the "Orders get edit_order_path doesn't render the :edit template for a nil role":

`Expected response to be a redirect to <http://www.example.com/users/sign_in> but was a redirect to <http://www.example.com/users/sign_in?locale=en>.
 Expected "http://www.example.com/users/sign_in" to be === "http://www.example.com/users/sign_in?locale=en".`

The expected result for this test is `"http://www.example.com/users/sign_in?locale=en".` including query "locale=en" but the actual path should be "http://www.example.com/en/users/sign_in" without query. Is this a bug in routs?

2021-03-14 07:51 UTC, NataMarkova commented
This is not completed test suites. After fixing the issue with the nil role, I'm going to add more tests.

2021-03-14 08:01 UTC, NataMarkova commented
Another issue I have is the test "Assignments get show_assignment_path redirects to the customer index path if the assignment id is invalid". The test throws the error:
`Expected response to be a redirect to <http://www.example.com/en/customers> but was a redirect to <http://www.example.com/en/customers/5000>.
  Expected "http://www.example.com/en/customers" to be === "http://www.example.com/en/customers/5000".`
Where is my mistake here?

2021-03-15 02:12 UTC, jrmcgarvey commented
Natalia, if you are not logged in, the assignments controller will redirect you to the sign in path.  Oh, also, when you create a PR and it is not complete, you should create it in draft mode so that it is not merged early.  Also, for the nil role test for edit order, it appears that the user is not signed in, so you are not really testing nil role.

2021-03-15 02:14 UTC, jrmcgarvey commented on app/helpers/application_helper.rb
> +    elsif volunteer?
Volunteers should get no access to the orders controller, so this elsif should be removed

2021-03-15 02:28 UTC, jrmcgarvey commented on app/helpers/application_helper.rb
> +      redirect_to new_user_session_path
The user is already signed in, so it does not make sense to redirect to the new_user_session_path.  In this case, you should redirect to the home_index_path.

2021-03-15 02:31 UTC, jrmcgarvey commented on app/controllers/orders_controller.rb
> +    def admin?
It seems like you are creating these methods over and over again for each controller.  You should put them in ApplicationController.rb, so that all controllers could inherit a single set of methods.  This is the DRY principal: Don't Repeat Yourself.

2021-03-15 02:32 UTC, jrmcgarvey commented on app/controllers/orders_controller.rb
> +  before_action :is_user_authorized_order?
You do not want the ? here.  That is for a method that returns true or false.

2021-03-15 02:38 UTC, jrmcgarvey commented on app/helpers/application_helper.rb
> +        flash[:error] = "You are not authorize for this operation."
Misspelling here.  Should be "You are not authorized for this operation."

2021-03-15 02:57 UTC, jrmcgarvey requested changes
Some changes needed, see comments

2021-03-15 03:54 UTC, NataMarkova commented on app/controllers/orders_controller.rb
> +    def admin?
The DRY principle is applied

2021-03-15 03:54 UTC, NataMarkova commented on app/controllers/orders_controller.rb
> +  before_action :is_user_authorized_order?
Done

2021-03-15 03:56 UTC, NataMarkova commented on app/helpers/application_helper.rb
> +        flash[:error] = "You are not authorize for this operation."
Misspelling is corrected.

2021-03-15 04:03 UTC, NataMarkova commented on app/helpers/application_helper.rb
> +    elsif volunteer?
Done.

2021-03-15 04:03 UTC, NataMarkova commented on app/helpers/application_helper.rb
> +      redirect_to new_user_session_path
Done.

2021-03-15 20:57 UTC, jrmcgarvey approved these changes
Ok

2021-03-15 20:57 UTC, merged