Service controller
CodeTheDream/not-alone pull request #89
Opened 2021-03-24 04:38 UTC by lena-aiu

Hi John, please review the changes in service_controller.rb, where I tried to create an access controller. I'm not sure that it's 100% right, because for example used (admin? || intern?) instead of (current_user.role.include?("administrator") || current_user.role.include?("intern")) @jrmcgarvey

2021-03-24 16:17 UTC, jrmcgarvey reviewed
This is basically correct, except for the one error identified below, but I think there is significant risk in merging this PR so soon before the demo, so I will not merge it right now.  Please fix the error so we can merge later.  I will also add that the code is kind of verbose -- one could reduce some of the logic and if/else statements.

2021-03-24 19:25 UTC, lena-aiu commented on app/controllers/services_controller.rb
> +      render :new
Okay, thank you

2021-03-24 19:27 UTC, lena-aiu commented
I just push changes that I made base on your comments @jrmcgarvey

2021-04-01 01:57 UTC, lena-aiu commented
@jrmcgarvey Please review the code. I fixed errors with the request tests for services, making changes in the access controller for services. Also fixed an error with the request test for categories, uncommenting the index method in categories_controller.rb.

2021-04-01 16:06 UTC, jrmcgarvey requested changes
There are three places where we have :new where it should be :edit.

2021-04-01 16:06 UTC, jrmcgarvey commented on app/controllers/categories_controller.rb
> +      render :new
This shoudl be render :edit

2021-04-01 16:06 UTC, jrmcgarvey commented on spec/requests/services_spec.rb
> +      expect(response).to render_template(:new)
this should be render_template(:edit)

2021-04-01 16:06 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +      render :new
This is still render :new it looks like.  It should be render :edit

2021-04-02 15:05 UTC, jrmcgarvey requested changes
Elena, I apologize, but I did find some more changes that are really needed.  These are marked in the review.  The main problem is the use of if nil?  which is not correct.

2021-04-02 15:05 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
The if nil? here is not correct.  I think what is meant is, if current_user.role.nil? .  If nil? just means, is the current instance of the services_controller nil, which is always false.  In any case, these three lines are unnecessary.  You should take them out and just start with if admin? || intern?

2021-04-02 15:05 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
Again, the if nil? is not correct, and these 3 lines ae not needed.

2021-04-02 15:05 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
again, the if ni? is not correct, and these three lines are unneeded.

2021-04-02 15:05 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
again, the if nil? is not correct, and these three lines are unneeded.

2021-04-02 15:05 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
same deal with the if nil?

2021-04-03 19:50 UTC, lena-aiu commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
Okay, I will make changes

2021-04-03 19:50 UTC, lena-aiu commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
Okay, I will make changes

2021-04-03 19:50 UTC, lena-aiu commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
Okay, I will make changes

2021-04-03 19:53 UTC, lena-aiu commented
@jrmcgarvey Hi John, I removed an unnecessary part of the code with if nil?, also changed the look of condition for admin and intern. Please review it. Thank you

2021-04-03 20:29 UTC, jrmcgarvey approved these changes
looks ok!

2021-04-03 20:29 UTC, merged