Navigation new
CodeTheDream/not-alone pull request #91
Opened 2021-03-27 22:54 UTC by lena-aiu

@jrmcgarvey Hi John, Now most content from Navbar on left justify. But when I resize the window Navbar content not hiding. I'm working on it. And need help. Thank you

2021-03-28 02:24 UTC, lena-aiu commented
@jrmcgarvey Hi John, please review the changes. Navbar content appears under toaster after resizing the page.

2021-03-29 02:11 UTC, lena-aiu commented
@jrmcgarvey HI John, please review changes in Navbar. E helped me with font color for the right side of the navbar and dropdown menu.

2021-04-01 02:02 UTC, lena-aiu commented
@jrmcgarvey Please review changes in the Navigation bar. I created a card on Trello board about the tab Other help, sometimes it is not working, and also attached the screenshots with error using development tools. E mentioned that it probably might be resolved on the back-end somehow.

2021-04-03 20:39 UTC, jrmcgarvey requested changes
There is now a merge conflict that must be resolved.  Also, I don't understand why the index view is commented out for categories -- I think one would want an index view.

2021-04-03 20:39 UTC, jrmcgarvey commented on app/controllers/categories_controller.rb
> +  # def index
Why is index commented out?  I think one would want an index view for categories.

2021-04-03 22:07 UTC, lena-aiu commented on app/controllers/categories_controller.rb
> +  # def index
Yes, I forgot to uncomment this, when I was working with the request test. I will fix.

2021-04-04 04:08 UTC, lena-aiu commented
@jrmcgarvey Hi John, please review the changes. I forgot to uncomment the index method when was working with the request test. Also, I resolved conflict for Create method in the categories controller. And made changes in categories_request_spec.rb for posting with invalid data.

2021-04-04 14:03 UTC, jrmcgarvey approved these changes
looks ok

2021-04-04 14:03 UTC, merged