Assignment controller
CodeTheDream/not-alone pull request #92
Opened 2021-04-02 05:14 UTC by lena-aiu

@jrmcgarvey Hi John, please review the code. 
Made changes in access controller assignments, changed show view for clients with a new assignment or new order base on the role.  Also I made changes in the request test for categories post with invalid data. In this version, we don't have the latest changes in Navigation. All changes with navbar in branch - navigationNew.
Thank you

2021-04-04 14:20 UTC, jrmcgarvey requested changes
We have regression of fixes from PR 89, with the if nil? error.  This may get fixed if the changes from the master are merged and you push again.

2021-04-04 14:20 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
problem here (regression)

2021-04-04 14:20 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
problem here (regression)

2021-04-04 14:20 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
problem here (regression of fix for nil? problem)

2021-04-04 14:20 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
same here

2021-04-04 14:20 UTC, jrmcgarvey commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
same here

2021-04-05 05:36 UTC, lena-aiu commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
It got fixed after merging the changes from the master

2021-04-05 05:37 UTC, lena-aiu commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
It got fixed after merging the changes from the master

2021-04-05 05:37 UTC, lena-aiu commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
It got fixed after merging the changes from the master

2021-04-05 05:37 UTC, lena-aiu commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
It got fixed after merging the changes from the master

2021-04-05 05:38 UTC, lena-aiu commented on app/controllers/services_controller.rb
> +    if  nil? || volunteer?
It got fixed after merging the changes from the master

2021-04-05 06:57 UTC, lena-aiu commented
@jrmcgarvey Hi John, all got fixed after merging the changes from the master. Also, I made small changes in navigation, using flex property to place English/Spanish on the same line as placed tabs for Home, About us, etc. And the responsiveness of the navbar working better, because not leaving the email address of the user outside the web page, which was resized.

2021-04-05 15:20 UTC, jrmcgarvey approved these changes
looks ok

2021-04-05 15:20 UTC, merged